swagger: "2.0"
info:
  title: dp-sessions-api
  description: "API for Sessions"
  version: 1.0.0
  license:
    name: "Open Government Licence v3.0"
    url: "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
basePath: "/v1"
schemes:
  - http
tags:
  - name: "session"
paths:
  /session:
    post:
      tags:
        - session
      summary: Create a session endpoint
      description: Creates a session and logs request back
      produces:
        - application/json
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/SessionResponse"
        400:
          description: Bad Request
          schema:
            $ref: "#/responses/BadRequest"

responses:
  InternalError:
    description: "Failed to process the request due to an internal error"