swagger: "2.0"
info:
  title: dp-sessions-api
  description: "API for Sessions"
  version: 1.0.0
  license:
    name: "Open Government Licence v3.0"
    url: "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
basePath: "/v1"
schemes:
  - http
tags:
  - name: "session"
paths:
  /session:
    post:
      tags:
        - session
      summary: Create a session endpoint
      description: Creates a session and logs request back
      produces:
        - application/json
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/GoodCreateSessionRequest"
        400:
          description: Bad Request
          schema:
            $ref: "#/definitions/BadCreateSessionRequest"
        500:
          description: Internal Server Error

definitions:
  GoodCreateSessionRequest:
    type: object
    properties:
      email:
        type: string
        example: me@email.com
  BadCreateSessionRequest:
    type: object
    