swagger: "2.0"
info:
  title: dp-sessions-api
  description: "API for Sessions"
  version: 1.0.0
  license:
    name: "Open Government Licence v3.0"
    url: "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
basePath: "/v1"
schemes:
  - http
tags:
  - name: "session"
paths:
  /session:
    post:
      tags:
        - session
      summary: Create a session endpoint
      description: Creates a new session for the provided user email.
      consumes:
        - application/json
      parameters:
        - in: body
          name: New session details
          description: Creates a new session for the provided user email.
          schema:
            $ref: "#/definitions/NewSessionRequest"
      produces:
        - application/json
      responses:
        201:
          description: Created
          headers:
            Content-Location:
              type: string
              description: The URI location of new session format "/session/{ID}"
        400:
          description: Bad Request
        500:
          description: Internal Server Error

definitions:
  NewSessionRequest:
    type: object
    properties:
      email:
        type: string
        example: user@email.com
    