// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/ONSdigital/dp-sessions-api/api"
	"github.com/ONSdigital/dp-sessions-api/session"
	"sync"
)

var (
	lockCacheMockDeleteAll  sync.RWMutex
	lockCacheMockGetByEmail sync.RWMutex
	lockCacheMockGetByID    sync.RWMutex
	lockCacheMockSetSession sync.RWMutex
)

// Ensure, that CacheMock does implement Cache.
// If this is not the case, regenerate this file with moq.
var _ api.Cache = &CacheMock{}

// CacheMock is a mock implementation of api.Cache.
//
//     func TestSomethingThatUsesCache(t *testing.T) {
//
//         // make and configure a mocked api.Cache
//         mockedCache := &CacheMock{
//             DeleteAllFunc: func() error {
// 	               panic("mock out the DeleteAll method")
//             },
//             GetByEmailFunc: func(email string) (*session.Session, error) {
// 	               panic("mock out the GetByEmail method")
//             },
//             GetByIDFunc: func(ID string) (*session.Session, error) {
// 	               panic("mock out the GetByID method")
//             },
//             SetSessionFunc: func(s *session.Session) error {
// 	               panic("mock out the SetSession method")
//             },
//         }
//
//         // use mockedCache in code that requires api.Cache
//         // and then make assertions.
//
//     }
type CacheMock struct {
	// DeleteAllFunc mocks the DeleteAll method.
	DeleteAllFunc func() error

	// GetByEmailFunc mocks the GetByEmail method.
	GetByEmailFunc func(email string) (*session.Session, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ID string) (*session.Session, error)

	// SetSessionFunc mocks the SetSession method.
	SetSessionFunc func(s *session.Session) error

	// calls tracks calls to the methods.
	calls struct {
		// DeleteAll holds details about calls to the DeleteAll method.
		DeleteAll []struct {
		}
		// GetByEmail holds details about calls to the GetByEmail method.
		GetByEmail []struct {
			// Email is the email argument value.
			Email string
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// ID is the ID argument value.
			ID string
		}
		// SetSession holds details about calls to the SetSession method.
		SetSession []struct {
			// S is the s argument value.
			S *session.Session
		}
	}
}

// DeleteAll calls DeleteAllFunc.
func (mock *CacheMock) DeleteAll() error {
	if mock.DeleteAllFunc == nil {
		panic("CacheMock.DeleteAllFunc: method is nil but Cache.DeleteAll was just called")
	}
	callInfo := struct {
	}{}
	lockCacheMockDeleteAll.Lock()
	mock.calls.DeleteAll = append(mock.calls.DeleteAll, callInfo)
	lockCacheMockDeleteAll.Unlock()
	return mock.DeleteAllFunc()
}

// DeleteAllCalls gets all the calls that were made to DeleteAll.
// Check the length with:
//     len(mockedCache.DeleteAllCalls())
func (mock *CacheMock) DeleteAllCalls() []struct {
} {
	var calls []struct {
	}
	lockCacheMockDeleteAll.RLock()
	calls = mock.calls.DeleteAll
	lockCacheMockDeleteAll.RUnlock()
	return calls
}

// GetByEmail calls GetByEmailFunc.
func (mock *CacheMock) GetByEmail(email string) (*session.Session, error) {
	if mock.GetByEmailFunc == nil {
		panic("CacheMock.GetByEmailFunc: method is nil but Cache.GetByEmail was just called")
	}
	callInfo := struct {
		Email string
	}{
		Email: email,
	}
	lockCacheMockGetByEmail.Lock()
	mock.calls.GetByEmail = append(mock.calls.GetByEmail, callInfo)
	lockCacheMockGetByEmail.Unlock()
	return mock.GetByEmailFunc(email)
}

// GetByEmailCalls gets all the calls that were made to GetByEmail.
// Check the length with:
//     len(mockedCache.GetByEmailCalls())
func (mock *CacheMock) GetByEmailCalls() []struct {
	Email string
} {
	var calls []struct {
		Email string
	}
	lockCacheMockGetByEmail.RLock()
	calls = mock.calls.GetByEmail
	lockCacheMockGetByEmail.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *CacheMock) GetByID(ID string) (*session.Session, error) {
	if mock.GetByIDFunc == nil {
		panic("CacheMock.GetByIDFunc: method is nil but Cache.GetByID was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: ID,
	}
	lockCacheMockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	lockCacheMockGetByID.Unlock()
	return mock.GetByIDFunc(ID)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//     len(mockedCache.GetByIDCalls())
func (mock *CacheMock) GetByIDCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	lockCacheMockGetByID.RLock()
	calls = mock.calls.GetByID
	lockCacheMockGetByID.RUnlock()
	return calls
}

// SetSession calls SetSessionFunc.
func (mock *CacheMock) SetSession(s *session.Session) error {
	if mock.SetSessionFunc == nil {
		panic("CacheMock.SetSessionFunc: method is nil but Cache.SetSession was just called")
	}
	callInfo := struct {
		S *session.Session
	}{
		S: s,
	}
	lockCacheMockSetSession.Lock()
	mock.calls.SetSession = append(mock.calls.SetSession, callInfo)
	lockCacheMockSetSession.Unlock()
	return mock.SetSessionFunc(s)
}

// SetSessionCalls gets all the calls that were made to SetSession.
// Check the length with:
//     len(mockedCache.SetSessionCalls())
func (mock *CacheMock) SetSessionCalls() []struct {
	S *session.Session
} {
	var calls []struct {
		S *session.Session
	}
	lockCacheMockSetSession.RLock()
	calls = mock.calls.SetSession
	lockCacheMockSetSession.RUnlock()
	return calls
}
