// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/ONSdigital/dp-sessions-api/api"
	"github.com/ONSdigital/dp-sessions-api/session"
	"sync"
)

var (
	lockSessionMockNew sync.RWMutex
)

// Ensure, that SessionMock does implement Session.
// If this is not the case, regenerate this file with moq.
var _ api.Session = &SessionMock{}

// SessionMock is a mock implementation of api.Session.
//
//     func TestSomethingThatUsesSession(t *testing.T) {
//
//         // make and configure a mocked api.Session
//         mockedSession := &SessionMock{
//             NewFunc: func(email string) (*session.Session, error) {
// 	               panic("mock out the New method")
//             },
//         }
//
//         // use mockedSession in code that requires api.Session
//         // and then make assertions.
//
//     }
type SessionMock struct {
	// NewFunc mocks the New method.
	NewFunc func(email string) (*session.Session, error)

	// calls tracks calls to the methods.
	calls struct {
		// New holds details about calls to the New method.
		New []struct {
			// Email is the email argument value.
			Email string
		}
	}
}

// New calls NewFunc.
func (mock *SessionMock) New(email string) (*session.Session, error) {
	if mock.NewFunc == nil {
		panic("SessionMock.NewFunc: method is nil but Session.New was just called")
	}
	callInfo := struct {
		Email string
	}{
		Email: email,
	}
	lockSessionMockNew.Lock()
	mock.calls.New = append(mock.calls.New, callInfo)
	lockSessionMockNew.Unlock()
	return mock.NewFunc(email)
}

// NewCalls gets all the calls that were made to New.
// Check the length with:
//     len(mockedSession.NewCalls())
func (mock *SessionMock) NewCalls() []struct {
	Email string
} {
	var calls []struct {
		Email string
	}
	lockSessionMockNew.RLock()
	calls = mock.calls.New
	lockSessionMockNew.RUnlock()
	return calls
}
