// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/ONSdigital/dp-sessions-api/api"
	"github.com/ONSdigital/dp-sessions-api/session"
	"sync"
)

var (
	lockUpdaterMockUpdate sync.RWMutex
)

// Ensure, that UpdaterMock does implement Updater.
// If this is not the case, regenerate this file with moq.
var _ api.Updater = &UpdaterMock{}

// UpdaterMock is a mock implementation of api.Updater.
//
//     func TestSomethingThatUsesUpdater(t *testing.T) {
//
//         // make and configure a mocked api.Updater
//         mockedUpdater := &UpdaterMock{
//             UpdateFunc: func(email string) (*session.Session, error) {
// 	               panic("mock out the Update method")
//             },
//         }
//
//         // use mockedUpdater in code that requires api.Updater
//         // and then make assertions.
//
//     }
type UpdaterMock struct {
	// UpdateFunc mocks the Update method.
	UpdateFunc func(email string) (*session.Session, error)

	// calls tracks calls to the methods.
	calls struct {
		// Update holds details about calls to the Update method.
		Update []struct {
			// Email is the email argument value.
			Email string
		}
	}
}

// Update calls UpdateFunc.
func (mock *UpdaterMock) Update(email string) (*session.Session, error) {
	if mock.UpdateFunc == nil {
		panic("UpdaterMock.UpdateFunc: method is nil but Updater.Update was just called")
	}
	callInfo := struct {
		Email string
	}{
		Email: email,
	}
	lockUpdaterMockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	lockUpdaterMockUpdate.Unlock()
	return mock.UpdateFunc(email)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//     len(mockedUpdater.UpdateCalls())
func (mock *UpdaterMock) UpdateCalls() []struct {
	Email string
} {
	var calls []struct {
		Email string
	}
	lockUpdaterMockUpdate.RLock()
	calls = mock.calls.Update
	lockUpdaterMockUpdate.RUnlock()
	return calls
}
